import time
print("It's Gonna Start Now... Move your text cursor focus to the")
print("Required Text Field")

time.sleep(30)

for i in range(100):
    pyautogui.press("Y")
    pyautogui.press("u")
    pyautogui.press("o")
    pyautogui.press("enter")
    pyautogui.press("a")
    pyautogui.press("r")
    pyautogui.press("e")
    pyautogui.press("enter")
    pyautogui.press("s")
    pyautogui.press("p")
    pyautogui.press("a")
    pyautogui.press("m")
    pyautogui.press("m")
    pyautogui.press("e")
    pyautogui.press("d")
    pyautogui.press("enter")
    pyautogui.press("b")
    pyautogui.press("y")
    pyautogui.press("enter")
    pyautogui.press("R")
    pyautogui.press("P")
    pyautogui.press("S")
